### ISSUE TITLE
consider putting segments on an official organisation

### ISSUE THREAD

**Issue by LinguList** [cldf/segments#19]
Given that the code will be further developed collaboratively, etc., but also for propagation, putting versions on Zenodo, etc., it seems logical to put the segments-code on an official organization, also adding a nice logo or whatever. Maybe an organization "orthography", "orthography-profiles", "orthoprofiles", would be a good idea? Alternatively, just make it part of clld, as this IS about cross-linguistically linked data, right?

**Comment by bambooforest** [comment]
The organization `segments` is taken. We could put it under the cookbook organization:

https://github.com/unicode-cookbook

**Comment by LinguList** [comment]
yep, seems like a good idea.
