### ISSUE TITLE
please draft a release and link to zenodo!

### ISSUE THREAD

**Issue by LinguList** [cldf/segments#22]
We can't quote the package if there's no DOI. So please draft a release and submit to Zenodo.

**Comment by LinguList** [comment]
given @xrotwang's substantial work on this, he should be listed as co-author. My role was minor, so listing me as a contributor (see policy in lingpy or concepticon) would be sufficient.

**Comment by LinguList** [comment]
Here's what I'd use as a bibtex right now, but a Zenodo-Link with a version is pending:

```
@Online{Moran2017a,
  author      = {Moran, Steven and Forkel, Robert},
  title       = {Segments. A Python implementation of orthography profiles},
  year        = {2017},
  url         = {https://github.com/bambooforest/},
  address     = {Zürich},
  contributor = {List, Johann-Mattis},
  publisher   = {Zurich Center for Linguistics},
  timestamp   = {2017.10.08},
}
```

**Comment by xrotwang** [comment]
We may want to wait until the Unicode book is published, so that published
algorithm and implementation are in sync.

Am 08.10.2017 18:30 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
Yes, cool with me! I was just thinking: I'd like to include a short note on orthography profiles in our lingpy tutorial. We'd need lingpy 2.6 for this anyway, and if we aim for submitting some time in November, we should have:

* segments version 1.0
* lingpy, version 2.6

at about the same time. I'll for now quote the bibtex as noted above in our tutorial draft. I'll also quote the version on Zenodo of Moran + Cysouw for the Unicode book. We can also just quote the github for the time being (if the tutorial passes review, we can rush when it goes for publication, no need to do this now, but we should be ready to have all things in order, so all things is versionized and ideally also on pypi).

**Comment by bambooforest** [comment]
@LinguList - yes we already discussed co-authorship, so we will also have to update segments on Pypi to include @xrotwang . I will list you also as contributor. 

The book needs a number of revisions that we plan to do asap (but I have a few things that I have to finish first), so November sounds like a reasonable goal. Regarding the current bibtex, I wouldn't use 
"Zurich Center for Linguistics" as publisher (they don't publish it). I suppose "Department of Comparative Linguistics" is better, but they also don't publish it...

I can also move the repo somewhere not under my personal github account, as you suggested before @LinguList , but `segments` seems to be taken and not used (argh).

**Comment by xrotwang** [comment]
@bambooforest we could move it to https://github.com/clld - which seems reasonable. https://github.com/lingpy may also work. In theory, a separate org per package would be the most flexible setup, but it also becomes unwieldy quickly ...

**Comment by xrotwang** [comment]
https://github.com/cldf/segments/releases/tag/v1.2.1
