### ISSUE TITLE
Use information provided in BIPA of CLTS to provide a state-of-the-art IPA segmentizer

### ISSUE THREAD

**Issue by LinguList** [cldf/segments#29]
Our code for BIPA lists more than 6000 different potentially valid ways to segment unsegmented IPA. This could be easily used to provide a first reliable segmentation script for "standard" IPA, but it may also be useful for initial orthography profile creation, provided that we list different aliases in the data as well as normalizations which could all be nicely added to the orthoprofile.

**Comment by xrotwang** [comment]
If I understand correctly, what you want is rather a state-of-the-art IPA orthography profile, no?

**Comment by LinguList** [comment]
yes, something along htese lines (if it's feasible in the end...)

**Comment by xrotwang** [comment]
Ok, and this profile could live in the CLTS package, right?

**Comment by LinguList** [comment]
why not, if you think it is consistent to have profiles there, the better. We could even handle more complex "orthographies" that are similar to sampa in the sense of being not easy to parse via segmented CLTS etc. Actually a good idea! In this case: both profiles, IPA-plain and X-Sampa should be there.

**Comment by xrotwang** [comment]
Yes, I think, conceptually it's simpler to have `segments` as the package implementing the orthography profile spec - so it changes whenever the spec changes, while CLTS is the package with knowledge about actual transcriptions and will change as more knowledge comes in. The only "transcription" `segments` knows about is UNICODE.
