### ISSUE TITLE
Using plain "?" as exception marker conflicts with e.g. X-SAMPA

### ISSUE THREAD

**Issue by xrotwang** [cldf/segments#32]
Since `?` is used as regular glyph in X-SAMPA, it shouldn't be used by [default as exception marker](https://github.com/cldf/segments/blob/012c1ffaddf8acca5d3cf6ba1b53df23cbe3d984/src/segments/tokenizer.py#L364).

**Comment by tresoldi** [comment]
Right. Luckily, I can't think of a common system which uses `#` (even though there probably is one). I can take care of this after the current bug fix.

**Comment by xrotwang** [comment]
I started to use `�` `U+FFFD REPLACEMENT MARKER` for this purpose instead of `?`.

**Comment by tresoldi** [comment]
Great! Was just about to ask if we shouldn't move to a specific Unicode charEm 16 de abr de 2018 5:03 PM, Robert Forkel <notifications@github.com> escreveu:I started to use � U+FFFD REPLACEMENT MARKER for this purpose instead of ?.
