### ISSUE TITLE
Citing Segments with DOI

### ISSUE THREAD

**Issue by HughP** [cldf/segments#38]
I was just about to cite segments with the DOI, but I noticed that the DOI strictly refers to version 1.1.1 whereas the pypi version is at 1.2.1. Is there a way to add versions to this Zenodo repo? perhaps through: http://blog.zenodo.org/2017/05/30/doi-versioning-launched/

Or maybe 1.2.1 just needs to also be committed to Zenodo. I mean we don't need 1.1.1 to go away, maybe someone is citing it.

**Comment by xrotwang** [comment]
There you go:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1283757.svg)](https://doi.org/10.5281/zenodo.1283757)

**Comment by xrotwang** [comment]
Btw.  to cite segments in a version-agnostic way you'd use https://doi.org/10.5281/zenodo.1051157

**Comment by HughP** [comment]
Thanks.
