### ISSUE TITLE
Logging in tokenizer.py ‘absorbs’ downstream logging

### ISSUE THREAD

**Issue by lfashby** [cldf/segments#47]
Importing the `segments` package leads to logging messages being absorbed by [global](https://github.com/cldf/segments/blob/master/src/segments/tokenizer.py#L16) `logging.basicConfig()` in `tokenizer.py`.

For example:
```
import logging

logging.basicConfig(level="INFO")
logging.info('Logging to console') # Will log to console.
```
While: 
```
import logging
import segments

logging.basicConfig(level="INFO")
logging.info('Logging to console') # Will NOT log to console.
```

**Comment by xrotwang** [comment]
If you want to use `segments` as library within a package, you may want to import it in function scope:
```python
>>> import logging
>>> logging.basicConfig(level="INFO")
>>> def f():
...     import segments
...     logging.info('Logging to console')
... 
>>> f()
INFO:root:Logging to console
```

**Comment by kylebgorman** [comment]
Just wanted to put a +1 on @lfashby's issue---importing a third-party module inside of a function call to avoid an unnecessary side effect is very ugly!

I've created a PR that removes the `basicConfig` call. As far as I can tell this has no negative consequences for the larger library. But perhaps there's some (untested) desirable side effect to calling `basicConfig` at module scope in tokenizer.py. If so you can ignore the PR.
